export const state = {
    sessionStatus: 'IDLE',
    sessionSeconds: 0,
    chosenTargetSeconds: 0,
    durationMode: 'range',
    endgameType: 'orgasm',
    rampdownSecondsLeft: 45,
    hrCurrent: 70,
    edges: 0,
    pauses: 0,
    peakHr: 70,
    isEdged: false,
    orgasmMode: false,
    savedMaxHr: null,
    activeMode: 'classic',
    alwaysFullStroke: false,
    lastHrTimestamp: Date.now(),
    strokerSpeed: 0,
    prostateSpeed: 0,
    strokeMin: 0,
    strokeMax: 100,
    ruinHoldSeconds: 0,
    edgeStallSeconds: 0,
    stallGuardEngaged: false,
    intensityValue: 50,
    history: [70],
    bleBattery: null,
    handyBattery: null,
    intifaceBattery: null,
    simEngaged: false,
    handyRole: localStorage.getItem('handy_role') || 'primary', // 'primary' | 'secondary' | 'off'
    handyMaxCap: parseInt(localStorage.getItem('handy_max_cap') || '100', 10),
    oracleState: 'IDLE',
    oracleTimer: 0,
    survivalSpeedFloor: 30,
    survivalTimer: 0,
    lastSpokenPrompt: ''
};

export const advancedSettings = {
    gammaCurve: 2.0,
    warmupMinutes: 5,
    edgeStrokeDepth: 100,
    cadenceBreathing: true,
    milkingWave: true,
    handyHwMin: 0,
    handyHwMax: 100,
    stallGuard: true,
    stallGuardSeconds: 8,
    dualDampening: true,
    dualDampeningBpm: 15,
    adaptiveDecay: true,
    decayEdgeCount: 2,
    decayBpm: 2,
    decayFloor: 105,
    voiceEnabled: false,
    micEnabled: false,
    customProfiles: {},
    learningProfile: {
        breakthroughEvents: 0,
        suggestedMaxHrOffset: 0
    }
};
